name: Atelier 1 – Fernet Secret

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      FERNET_KEY: ${{ secrets.FERNET_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Installer les dépendances
        run: pip install cryptography

      - name: Créer le fichier de test
        run: echo "Message Top secret !" > secret.txt

      - name: Chiffrer
        run: python app/fernet_atelier1.py encrypt secret.txt secret.enc

      - name: Déchiffrer
        run: python app/fernet_atelier1.py decrypt secret.enc secret.dec.txt

      - name: Vérifier le résultat
        run: cat secret.dec.txt
